import * as snarkjs from "snarkjs";

export type ProofForContract = {
  pA: [bigint, bigint];
  pB: [[bigint, bigint], [bigint, bigint]];
  pC: [bigint, bigint];
};

export type WithdrawalProofInput = {
  root: bigint;
  nullifierHash: bigint;
  recipient: bigint;
  fee: bigint;
  secret: bigint;
  nullifier: bigint;
  pathElements: bigint[];
  pathIndices: number[];
};

type SnarkProof = {
  pi_a: string[];
  pi_b: string[][];
  pi_c: string[];
  protocol: string;
};

type SnarkResult = {
  proof: SnarkProof;
  publicSignals: string[];
};

function formatProofForContract(proof: SnarkProof): ProofForContract {
  // snarkjs uses string representations for bigints in proof output
  // pB is transposed for EVM — see groth16ExportSolidityCallData
  return {
    pA: [BigInt(proof.pi_a[0]), BigInt(proof.pi_a[1])],
    pB: [
      [BigInt(proof.pi_b[0][1]), BigInt(proof.pi_b[0][0])],
      [BigInt(proof.pi_b[1][1]), BigInt(proof.pi_b[1][0])],
    ],
    pC: [BigInt(proof.pi_c[0]), BigInt(proof.pi_c[1])],
  };
}

export async function generateWithdrawalProof(
  input: WithdrawalProofInput,
): Promise<ProofForContract> {
  // NIGHT-SHIFT-REVIEW: WASM and zkey must be served as static assets in public/circuits/
  // These files are generated by: bash scripts/compile-circuit.sh && bash scripts/generate-verifier.sh
  const wasmPath = "/circuits/withdraw.wasm";
  const zkeyPath = "/circuits/withdraw_final.zkey";

  const circuitInput = {
    root: input.root.toString(),
    nullifierHash: input.nullifierHash.toString(),
    recipient: input.recipient.toString(),
    fee: input.fee.toString(),
    secret: input.secret.toString(),
    nullifier: input.nullifier.toString(),
    pathElements: input.pathElements.map((e) => e.toString()),
    pathIndices: input.pathIndices,
  };

  const { proof } = (await snarkjs.groth16.fullProve(
    circuitInput,
    wasmPath,
    zkeyPath,
  )) as SnarkResult;

  return formatProofForContract(proof);
}
